apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must be in the form: <plural>.<group>
  name: k21apps.k21academy.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k21academy.com
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. 
    kind: K21app
    # singular name to be used as an alias on the CLI
    singular: k21app
    # plural name in the URL: /apis/<group>/<version>/<plural>
    plural: k21apps
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
