apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport-service
spec:
  selector:
    tier: monitoring
    name: prometheus-exporter
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
