apiVersion: apps/v1
kind: Deployment 
metadata:
  name: db1
spec:
  selector:
    matchLabels:
      dish: samosa
  replicas:  2
  template:
    metadata:
      labels:
        dish: samosa
    spec:
      containers:
      - name: dbb
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: MYSQL_DATABASE

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: MYSQL_ROOT_PASSWORD
