kind: Pod
apiVersion: v1
metadata:
  name: mypod2
  namespace: default
spec:
  containers:
  - name: mypod2
    image: nginx:1.15.5
    env: 
      - name: date
        valueFrom:
          configMapKeyRef:
            name: myconfig1
            key: date
      - name: hostname1
        valueFrom:
          configMapKeyRef:
            name: myconfig1
            key: hostname
      - name: home1
        valueFrom:
          configMapKeyRef:
            name: myconfig1
            key: HOME

      - name: vegdish
        valueFrom:
          configMapKeyRef:
            name: myconfig1
            key: dish

      - name: academy
        valueFrom:
          configMapKeyRef:
            name: myconfig1
            key: env
