kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: test1
  namespace: development
subjects:
- kind: ServiceAccount
  name: test1
  apiGroup: ""
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
